name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js v20.14.0
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'

      - name: Install Node.js packages with yarn
        run: yarn install

      - name: Install Playwright and Vitest
        run: |
          npm install -g playwright
          npm install -g vitest

      - name: Install browsers for Playwright
        run: npx playwright install

      - name: Run unit tests
        run: yarn vitest

      - name: Run end-to-end tests
        run: node integration-tests/ticTacToe.mjs

      - name: Deploy to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . 

      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results.xml
